import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Check, ChevronDown, Menu, Minus, Plus, Search, ShieldCheck, Truck, X } from 'lucide-react';
import './styles.css';

const company = {
  name: '澧林(沙田)有限公司',
  email: 'lilinshatian@outlook.com',
  address: 'SHOP NO 248-250,2/F. WO CHE PLAZA,SHA TIN,HONGKONG',
};

const categories = [
  { id: 'furniture', label: 'Furniture', note: 'Grounded pieces for every room' },
  { id: 'soft', label: 'Soft Furnishings', note: 'Texture, comfort and quiet colour' },
  { id: 'decor', label: 'Decor & Lighting', note: 'Small details, warm atmosphere' },
];

const products = [
  ['furniture-01.webp', 'Mini Fridge', 'Compact Appliances', 189, 'furniture', 'A quiet, compact refrigerator for studio kitchens and guest rooms.'],
  ['furniture-02.webp', 'Walnut Platform Bed', 'Bedroom Furniture', 199, 'furniture', 'A low-profile solid wood bed with a softly rounded headboard.'],
  ['furniture-03.webp', 'Tall Oak Wardrobe', 'Bedroom Furniture', 899, 'furniture', 'Generous hanging space with a warm oak finish and clean lines.'],
  ['furniture-04.webp', 'Everyday Dining Table', 'Dining Furniture', 429, 'furniture', 'A sturdy four-person table for weekday meals and slow weekends.'],
  ['furniture-05.webp', 'Countertop Water Dispenser', 'Kitchen Appliances', 129, 'furniture', 'A slim filtered-water station with hot and cool dispensing.'],
  ['furniture-06.webp', 'Slatted Media Console', 'Living Room Furniture', 519, 'furniture', 'Cable-friendly storage with tactile slatted doors and open shelving.'],
  ['furniture-07.webp', 'Olive Six-Drawer Dresser', 'Bedroom Furniture', 479, 'furniture', 'Six smooth drawers in a muted olive finish for everyday storage.'],
  ['furniture-08.webp', 'Cane Door Sideboard', 'Dining Furniture', 629, 'furniture', 'A refined sideboard with woven cane panels and adjustable shelves.'],
  ['furniture-09.webp', 'Open Oak Bookcase', 'Office Furniture', 349, 'furniture', 'Five open shelves for books, baskets and collected objects.'],
  ['furniture-10.webp', 'Slim Writing Desk', 'Office Furniture', 249, 'furniture', 'A compact desk with a drawer and a footrest rail for small spaces.'],
  ['soft-01.webp', 'Washed Linen Curtains', 'Curtains', 68, 'soft', 'Light-filtering linen panels with a calm, natural drape.'],
  ['soft-02.webp', 'Flatweave Wool Rug', 'Rugs', 149, 'soft', 'A low-pile woven rug that layers easily under dining or lounge furniture.'],
  ['soft-03.webp', 'Pebble Knit Cushion', 'Cushions', 32, 'soft', 'A tactile cotton cushion in a muted moss tone.'],
  ['soft-04.webp', 'Striped Cotton Throw', 'Throws', 54, 'soft', 'A breathable cotton throw with a soft fringe edge.'],
  ['soft-05.webp', 'Linen Folding Screen', 'Screens', 138, 'soft', 'A freestanding textile screen that softly divides a room.'],
  ['soft-06.webp', 'Sheer Voile Curtains', 'Sheer Curtains', 48, 'soft', 'An airy voile layer that brings privacy without blocking daylight.'],
  ['soft-07.webp', 'Ivory Venetian Blind', 'Blinds', 76, 'soft', 'Easy-clean slats for gentle light control in home offices and bedrooms.'],
  ['soft-08.webp', 'Textured Wallcovering', 'Wallcovering', 92, 'soft', 'A subtle woven-look roll for a warm, quiet feature wall.'],
  ['soft-09.webp', 'Rust Tufted Seat Cushion', 'Seat Cushions', 36, 'soft', 'A thick tie-on cushion for dining chairs, benches and window seats.'],
  ['soft-10.webp', 'Round Floor Cushion', 'Floor Cushions', 44, 'soft', 'A generous low seat for reading corners and relaxed hosting.'],
  ['decor-01.webp', 'Stone Reed Diffuser', 'Fragrance', 28, 'decor', 'A low-key reed diffuser with a soft cedar and amber scent.'],
  ['decor-02.webp', 'Linen Shade Table Lamp', 'Table Lamps', 79, 'decor', 'Warm ambient light with a hand-finished fabric shade.'],
  ['decor-03.webp', 'Brass Stem Floor Lamp', 'Floor Lamps', 149, 'decor', 'A slender standing lamp that adds a warm pool of light beside seating.'],
  ['decor-04.webp', 'Arched Wall Sconce', 'Wall Lamps', 69, 'decor', 'A compact sconce with a brushed metal arm and linen shade.'],
  ['decor-05.webp', 'Pivot Desk Lamp', 'Desk Lamps', 58, 'decor', 'Directional task lighting with a weighted base and adjustable arm.'],
  ['decor-06.webp', 'Travertine Face Clock', 'Decorative Clocks', 88, 'decor', 'A quiet sculptural clock with a stone-look face and slim hands.'],
  ['decor-07.webp', 'Walnut Valet Tray', 'Decorative Objects', 64, 'decor', 'A softly rounded wood tray for keys, fragrance and bedside essentials.'],
  ['decor-08.webp', 'Brass Candle Holder', 'Candle Holders', 34, 'decor', 'A balanced metal holder designed for a single pillar candle.'],
  ['decor-09.webp', 'Looped Sculpture', 'Decorative Objects', 52, 'decor', 'A tactile abstract form for shelves, consoles and bedside tables.'],
  ['decor-10.webp', 'Pleated Pendant Lamp', 'Pendant Lamps', 126, 'decor', 'A pleated fabric shade that casts a warm, generous glow.'],
].map(([image, name, subcategory, price, category, description], index) => ({ id: index + 1, image: `/products/${image}`, name, subcategory, price, category, description }));

const legalPages = {
  payment: { title: 'Payment', intro: 'Secure checkout for your Lelyn Home order.', sections: [['Accepted payment methods', 'We currently show PayPal, Visa and major credit or debit cards at checkout. The payment buttons in this storefront are a front-end demo entry point and must be connected to your merchant account before accepting live payments.'], ['Order confirmation', 'Your order summary, delivery address and payment choice are reviewed before submission. A confirmation email should be sent by the connected payment provider or order system.']] },
  returns: { title: 'Returns & Refunds', intro: 'A clear, fair process for bringing an order home.', sections: [['Return window', 'Contact us within 14 days of delivery to request a return. Items should be unused, clean and in their original packaging where practical.'], ['Refunds', 'Approved refunds are returned to the original payment method after the item is received and checked. Delivery fees are refundable when the item arrived damaged or materially different from its listing.'], ['Exclusions', 'Made-to-order items, used textiles and items damaged after delivery may be excluded. We will explain the reason and available options by email.']] },
  cancellation: { title: 'Cancellation Policy', intro: 'Change your mind? Let us know as early as possible.', sections: [['Before dispatch', 'Orders can be cancelled by contacting lilinshatian@outlook.com before dispatch. We will confirm whether cancellation is possible.'], ['After dispatch', 'Once an order is with the carrier, use the return process after delivery.']] },
  about: { title: 'About Lelyn Home', intro: 'Everyday home pieces selected for useful beauty.', sections: [['Our approach', 'Lelyn Home brings furniture, textiles and small objects together in a considered catalogue for modern Hong Kong homes. We look for useful proportions, honest materials and calm colour.'], ['Company', `${company.name} operates from ${company.address}. For questions, email ${company.email}.`]] },
  shipping: { title: 'Shipping Policy', intro: 'Practical delivery information for your order.', sections: [['Processing', 'Orders are prepared within 2–4 business days. Oversize furniture may require a delivery appointment.'], ['Delivery', 'Estimated delivery windows and carrier details are shown at checkout when available. Remote or restricted-access locations may require an additional delivery arrangement.'], ['Damage on arrival', 'Photograph the packaging and item, then contact us within 48 hours so we can help with a replacement or refund.']] },
  tracking: { title: 'Order Tracking', intro: 'Keep an eye on your delivery.', sections: [['How it works', 'After dispatch, your tracking number is sent to the email address used at checkout. Enter that number on the carrier website or contact us at lilinshatian@outlook.com for help.'], ['Order details', 'Keep your order number available when contacting support so we can locate the correct shipment.']] },
  privacy: { title: 'Privacy Policy', intro: 'Your information is used to fulfil orders and support your experience.', sections: [['Information we collect', 'We may collect contact, shipping, order and payment-status information needed to process a purchase. Card details should be handled by the connected payment provider.'], ['Use and retention', 'We use order information for fulfilment, support, fraud prevention and legal obligations. We retain information only as long as reasonably required for these purposes.'], ['Your choices', `For privacy questions, contact ${company.email}.`]] },
  dmca: { title: 'DMCA', intro: 'Notice and contact process for copyright concerns.', sections: [['Notice', 'A copyright notice should identify the work, the allegedly infringing material, your contact details and a good-faith statement that the use is not authorised.'], ['Contact', `Send notices to ${company.email} with the subject “DMCA Notice”. We will review complete notices and respond as appropriate.`]] },
  terms: { title: 'Terms of Service', intro: 'These terms describe the rules for using Lelyn Home and placing orders.', sections: [
    ['1. Agreement', 'By using this site, you agree to these terms and the policies linked from the footer.'], ['2. Eligibility', 'You must be able to enter a binding agreement under the laws that apply to you.'], ['3. Product information', 'We aim for accurate product descriptions, dimensions and images. Colour may vary by display.'], ['4. Pricing', 'Prices are shown in US dollars unless stated otherwise and may change before an order is submitted.'], ['5. Orders', 'An order request is subject to availability and confirmation.'], ['6. Payment', 'Payment is processed through the selected provider. Do not send full card details by email.'], ['7. Shipping', 'Delivery windows are estimates and may be affected by carriers, access restrictions or events outside our control.'], ['8. Inspection', 'Please inspect packages promptly and contact us about damage with photographs.'], ['9. Returns', 'Returns are handled under the Returns & Refunds Policy.'], ['10. Cancellations', 'Cancellation requests are handled under the Cancellation Policy.'], ['11. Account details', 'You are responsible for keeping submitted contact and delivery details accurate.'], ['12. Acceptable use', 'Do not misuse the site, interfere with its operation or attempt unauthorised access.'], ['13. Intellectual property', 'Site content, photography and written material belong to their respective owners and may not be reused without permission.'], ['14. Third-party services', 'Payment and delivery providers may apply their own terms and privacy policies.'], ['15. Disclaimers', 'The site is provided on an as-available basis and product use should follow supplied instructions.'], ['16. Liability', 'To the extent permitted by law, liability is limited to the value of the relevant order.'], ['17. Contact and changes', `We may update these terms. Questions can be sent to ${company.email}.`],
  ] },
};

function money(value) { return `$${value.toFixed(2)}`; }

function App() {
  const [view, setView] = useState('home');
  const [category, setCategory] = useState('all');
  const [cart, setCart] = useState([]);
  const [cartOpen, setCartOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [checkout, setCheckout] = useState(false);

  useEffect(() => {
    const sync = () => {
      const hash = window.location.hash.replace('#/', '');
      if (hash === 'admin') setView('admin');
      else if (hash === 'checkout') setCheckout(true);
      else if (hash.startsWith('legal/')) setView(hash.replace('legal/', ''));
      else setView(hash || 'home');
    };
    sync(); window.addEventListener('hashchange', sync); return () => window.removeEventListener('hashchange', sync);
  }, []);

  const visibleProducts = useMemo(() => products.filter((item) => (category === 'all' || item.category === category) && `${item.name} ${item.subcategory}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  const cartItems = cart.map((item) => ({ ...item, product: products.find((product) => product.id === item.id) })).filter((item) => item.product);
  const cartTotal = cartItems.reduce((sum, item) => sum + item.product.price * item.qty, 0);

  const addToCart = (product, direct = false) => {
    setCart((current) => current.some((item) => item.id === product.id) ? current.map((item) => item.id === product.id ? { ...item, qty: item.qty + 1 } : item) : [...current, { id: product.id, qty: 1 }]);
    if (direct) { setCheckout(true); window.location.hash = 'checkout'; } else setCartOpen(true);
  };
  const updateQty = (id, delta) => setCart((current) => current.map((item) => item.id === id ? { ...item, qty: Math.max(0, item.qty + delta) } : item).filter((item) => item.qty));
  const go = (next) => { setCheckout(false); setView(next); window.location.hash = next === 'home' ? '' : next; window.scrollTo({ top: 0, behavior: 'smooth' }); };

  if (view === 'admin') return <Admin />;
  if (checkout) return <Checkout cartItems={cartItems} cartTotal={cartTotal} onBack={() => { setCheckout(false); go('home'); }} />;
  if (legalPages[view]) return <><Header cartCount={cartItems.reduce((sum, item) => sum + item.qty, 0)} onCart={() => setCartOpen(true)} onHome={() => go('home')} onNavigate={go} /><LegalPage page={legalPages[view]} /><Footer go={go} /><CartDrawer open={cartOpen} setOpen={setCartOpen} items={cartItems} total={cartTotal} updateQty={updateQty} onCheckout={() => { setCartOpen(false); setCheckout(true); window.location.hash = 'checkout'; }} /></>;

  return <div className="app-shell"><Header cartCount={cartItems.reduce((sum, item) => sum + item.qty, 0)} onCart={() => setCartOpen(true)} onHome={() => go('home')} onNavigate={go} />
    <main>
      <section className="hero"><div className="hero-copy"><p className="eyebrow">LELYN HOME / 2026 EDIT</p><h1>Make room for the life you live.</h1><p className="hero-lede">Furniture, textiles and quiet objects chosen for the everyday rituals that make a home yours.</p><button className="button button-dark" onClick={() => { setCategory('furniture'); document.getElementById('catalog').scrollIntoView({ behavior: 'smooth' }); }}>Explore furniture <ArrowRight size={16} /></button></div><div className="hero-stack"><div className="hero-card hero-card-large"><span>THE QUIET EDIT</span><strong>Warm wood,<br />soft light.</strong></div><div className="hero-card hero-card-small"><span>AT HOME</span><strong>Good things<br />within reach.</strong></div></div></section>
      <section className="trust-strip"><span><Truck size={18} /> Thoughtful delivery</span><span><ShieldCheck size={18} /> Secure checkout entry</span><span><Check size={18} /> 14-day returns</span></section>
      <section className="intro"><p className="eyebrow">A SMALLER, BETTER CATALOGUE</p><h2>Pieces that settle in.</h2><p>Start with the essentials, then add the details that make a room feel considered. Everything is arranged in calm, useful collections.</p></section>
      <section className="category-rail">{categories.map((item) => <button key={item.id} className={category === item.id ? 'category-card active' : 'category-card'} onClick={() => { setCategory(item.id); document.getElementById('catalog').scrollIntoView({ behavior: 'smooth' }); }}><span>{item.label}</span><small>{item.note}</small><ArrowRight size={17} /></button>)}</section>
      <section className="catalog" id="catalog"><div className="catalog-head"><div><p className="eyebrow">SHOP THE EDIT</p><h2>{category === 'all' ? 'All pieces' : categories.find((item) => item.id === category)?.label}</h2></div><div className="catalog-tools"><label className="search-box"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search pieces" /></label><button className="select-button" onClick={() => setCategory(category === 'all' ? 'furniture' : 'all')}>{category === 'all' ? 'Featured' : 'All pieces'} <ChevronDown size={15} /></button></div></div><div className="product-grid">{visibleProducts.map((product) => <ProductCard key={product.id} product={product} addToCart={addToCart} />)}</div></section>
      <section className="story-band"><div><p className="eyebrow">THE LELYN STANDARD</p><h2>Useful first.<br />Beautiful always.</h2></div><p>Our catalogue is built around durable forms, warm materials and prices that make sense for everyday homes. Take what works, leave what does not.</p></section>
    </main><Footer go={go} /><CartDrawer open={cartOpen} setOpen={setCartOpen} items={cartItems} total={cartTotal} updateQty={updateQty} onCheckout={() => { setCartOpen(false); setCheckout(true); window.location.hash = 'checkout'; }} /></div>;
}

function Header({ cartCount, onCart, onHome, onNavigate }) { const shop = () => { onHome(); setTimeout(() => document.getElementById('catalog')?.scrollIntoView({ behavior: 'smooth' }), 0); }; return <header className="site-header"><button className="wordmark" onClick={onHome}>LELYN<span>HOME</span></button><nav><button onClick={onHome}>Home</button><button onClick={shop}>Shop</button><button onClick={() => onNavigate?.('about')}>About</button><button onClick={() => onNavigate?.('legal/shipping')}>Delivery</button></nav><div className="header-actions"><button className="icon-button mobile-menu"><Menu size={19} /></button><button className="cart-button" onClick={onCart}>Bag <span>{cartCount}</span></button></div></header>; }

function ProductCard({ product, addToCart }) { return <article className="product-card"><div className="product-image-wrap"><img src={product.image} alt={product.name} /><span className="product-tag">{product.subcategory}</span></div><div className="product-info"><div><h3>{product.name}</h3><p>{product.description}</p></div><strong>{money(product.price)}</strong></div><div className="product-actions"><button className="button button-light" onClick={() => addToCart(product)}>Add to Cart</button><button className="button button-dark" onClick={() => addToCart(product, true)}>Buy Now <span>— {money(product.price)}</span></button></div></article>; }

function CartDrawer({ open, setOpen, items, total, updateQty, onCheckout }) { return <div className={open ? 'drawer-layer open' : 'drawer-layer'}><button className="drawer-backdrop" onClick={() => setOpen(false)} aria-label="Close cart" /><aside className="cart-drawer"><div className="drawer-head"><div><p className="eyebrow">YOUR BAG</p><h2>{items.reduce((sum, item) => sum + item.qty, 0)} items</h2></div><button className="icon-button" onClick={() => setOpen(false)}><X size={20} /></button></div>{items.length === 0 ? <div className="empty-state"><p>Your bag is ready for something good.</p><button className="button button-dark" onClick={() => setOpen(false)}>Continue shopping</button></div> : <><div className="cart-list">{items.map(({ product, qty }) => <div className="cart-line" key={product.id}><img src={product.image} alt="" /><div><h3>{product.name}</h3><p>{money(product.price)}</p><div className="qty"><button onClick={() => updateQty(product.id, -1)}><Minus size={13} /></button><span>{qty}</span><button onClick={() => updateQty(product.id, 1)}><Plus size={13} /></button></div></div><strong>{money(product.price * qty)}</strong></div>)}</div><div className="drawer-foot"><div><span>Subtotal</span><strong>{money(total)}</strong></div><small>Taxes and delivery are calculated at checkout.</small><button className="button button-dark full-width" onClick={onCheckout}>Go to checkout <ArrowRight size={16} /></button></div></>}</aside></div>; }

function Checkout({ cartItems, cartTotal, onBack }) { const [submitted, setSubmitted] = useState(false); return <div className="checkout-page"><header className="checkout-header"><button className="wordmark" onClick={onBack}>LELYN<span>HOME</span></button><span>Checkout</span></header><main className="checkout-layout">{submitted ? <div className="confirmation"><Check size={28} /><p className="eyebrow">DEMO ORDER READY</p><h1>Your order is prepared.</h1><p>This front-end checkout is ready to connect to PayPal or a card processor. No payment was captured.</p><button className="button button-dark" onClick={onBack}>Return to shop</button></div> : <><div className="checkout-form"><p className="eyebrow">CHECKOUT</p><h1>Almost home.</h1><label>Email address<input type="email" placeholder="you@example.com" /></label><label>Delivery address<input placeholder="Street, city, region" /></label><div className="form-row"><label>Country<input defaultValue="Hong Kong" /></label><label>Postal code<input placeholder="000000" /></label></div><div className="pay-title"><span>Payment method</span><small>Demo provider entry</small></div><div className="payment-options"><button><b>PayPal</b><span>Pay with PayPal</span></button><button><b>VISA</b><span>Visa or credit card</span></button><button><b>Card</b><span>Other credit or debit card</span></button></div><button className="button button-dark full-width" onClick={() => setSubmitted(true)}>Place demo order <ArrowRight size={16} /></button><p className="form-note">By continuing, you agree to the <a href="#legal/terms">Terms of Service</a> and <a href="#legal/privacy">Privacy Policy</a>.</p></div><div className="checkout-summary"><p className="eyebrow">ORDER SUMMARY</p>{cartItems.length === 0 ? <p>Your bag is empty. Return to the shop to choose a piece.</p> : cartItems.map(({ product, qty }) => <div className="summary-line" key={product.id}><img src={product.image} alt="" /><span>{product.name}<small>Qty {qty}</small></span><strong>{money(product.price * qty)}</strong></div>)}<div className="summary-total"><span>Total</span><strong>{money(cartTotal)}</strong></div></div></>}</main></div>; }

function LegalPage({ page }) { return <main className="legal-page"><p className="eyebrow">LELYN HOME / INFORMATION</p><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p><div className="legal-content">{page.sections.map(([title, content]) => <section key={title}><h2>{title}</h2><p>{content}</p></section>)}</div></main>; }

function Footer({ go }) { const legal = [['Payment', 'payment'], ['Returns & Refunds', 'returns'], ['Cancellation', 'cancellation'], ['Shipping', 'shipping'], ['Order Tracking', 'tracking'], ['Terms of Service', 'terms'], ['Privacy Policy', 'privacy'], ['DMCA', 'dmca']]; return <footer className="site-footer"><div className="footer-top"><div><button className="wordmark light" onClick={() => go('home')}>LELYN<span>HOME</span></button><p className="footer-about">Thoughtful pieces for everyday rooms.<br />A calmer way to shop for home.</p></div><div className="footer-contact"><p className="eyebrow">CONTACT</p><p>{company.name}</p><a href={`mailto:${company.email}`}>{company.email}</a><p>{company.address}</p></div></div><div className="footer-columns"><div><p className="footer-label">Shop</p><button onClick={() => { window.location.hash = 'home'; setTimeout(() => document.getElementById('catalog')?.scrollIntoView({ behavior: 'smooth' }), 0); }}>All pieces</button><button onClick={() => { window.location.hash = 'home'; setTimeout(() => document.getElementById('catalog')?.scrollIntoView({ behavior: 'smooth' }), 0); }}>Furniture</button><button onClick={() => { window.location.hash = 'home'; setTimeout(() => document.getElementById('catalog')?.scrollIntoView({ behavior: 'smooth' }), 0); }}>Soft furnishings</button></div><div><p className="footer-label">Help</p>{legal.slice(0, 5).map(([label, id]) => <button key={id} onClick={() => go(`legal/${id}`)}>{label}</button>)}</div><div><p className="footer-label">Company</p>{legal.slice(5).map(([label, id]) => <button key={id} onClick={() => go(`legal/${id}`)}>{label}</button>)}<button onClick={() => go('about')}>About us</button><button onClick={() => { window.location.hash = 'admin'; }}>Admin demo</button></div></div><div className="footer-bottom"><span>© 2026 {company.name}</span><span>Hong Kong · USD</span></div></footer>; }

function Admin() { const [loggedIn, setLoggedIn] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const valid = email === 'admin@lelynhome.com' && password === 'LelynHome2026!'; return <div className="admin-page">{!loggedIn ? <div className="admin-login"><p className="eyebrow">LELYN HOME / ADMIN DEMO</p><h1>Welcome back.</h1><p>Use the demo credentials supplied with this project.</p><label>Email<input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="admin@lelynhome.com" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="LelynHome2026!" /></label><button className="button button-dark full-width" onClick={() => valid && setLoggedIn(true)}>Sign in <ArrowRight size={16} /></button><a href="#">Back to storefront</a></div> : <div className="admin-dashboard"><div className="admin-top"><div><p className="eyebrow">ADMIN DEMO</p><h1>Good morning.</h1></div><a href="#">View storefront</a></div><div className="admin-stats"><div><span>Orders this month</span><strong>24</strong><small>+12% from last month</small></div><div><span>Catalog pieces</span><strong>30</strong><small>3 collections live</small></div><div><span>Gross sales</span><strong>$8,420</strong><small>Demo data</small></div></div><div className="admin-panel"><div><p className="eyebrow">RECENT ORDERS</p><h2>Order activity</h2></div>{['#LH-1048 · Maya C.', '#LH-1047 · Daniel W.', '#LH-1046 · Chloe L.'].map((order, i) => <div className="order-row" key={order}><span>{order}</span><small>{i === 0 ? 'Processing' : 'Delivered'}</small><strong>{['$429.00', '$149.00', '$68.00'][i]}</strong></div>)}</div><p className="admin-note">Front-end demonstration only. Connect a server, database and authenticated payment/order services before using this for live operations.</p></div>}</div>; }

createRoot(document.getElementById('root')).render(<App />);
